2022-07-05 14:04:12,242 INFO    MainThread:248316 [wandb_setup.py:_flush():76] Configure stats pid to 248316
2022-07-05 14:04:12,243 INFO    MainThread:248316 [wandb_setup.py:_flush():76] Loading settings from /nfs/stak/users/noelt/.config/wandb/settings
2022-07-05 14:04:12,245 INFO    MainThread:248316 [wandb_setup.py:_flush():76] Loading settings from /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/settings
2022-07-05 14:04:12,246 INFO    MainThread:248316 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-05 14:04:12,247 INFO    MainThread:248316 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-05 14:04:12,248 INFO    MainThread:248316 [wandb_init.py:_log_setup():461] Logging user logs to /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220705_140412-2iq7gliv/logs/debug.log
2022-07-05 14:04:12,249 INFO    MainThread:248316 [wandb_init.py:_log_setup():462] Logging internal logs to /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220705_140412-2iq7gliv/logs/debug-internal.log
2022-07-05 14:04:12,250 INFO    MainThread:248316 [wandb_init.py:init():495] calling init triggers
2022-07-05 14:04:12,251 INFO    MainThread:248316 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2022-07-05 14:04:12,252 INFO    MainThread:248316 [wandb_init.py:init():515] re-initializing run, found existing run on stack: 3376w4f6
2022-07-05 14:04:12,257 INFO    MainThread:248316 [wandb_run.py:_finish():1680] finishing run tnoel20/Thomas-Masters-Project/3376w4f6
2022-07-05 14:04:12,258 INFO    MainThread:248316 [jupyter.py:save_history():435] not saving jupyter history
2022-07-05 14:04:12,259 INFO    MainThread:248316 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-05 14:04:12,259 INFO    MainThread:248316 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2022-07-05 14:04:12,259 INFO    MainThread:248316 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-07-05 14:04:12,260 INFO    MainThread:248316 [wandb_run.py:_restore():1834] restore
2022-07-05 14:04:12,794 INFO    MainThread:248316 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 644
  total_bytes: 644
}

2022-07-05 14:04:12,978 INFO    MainThread:248316 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 644
  total_bytes: 644
}

2022-07-05 14:04:18,079 INFO    MainThread:248316 [wandb_run.py:_on_finish():1991] got exit ret: None
2022-07-05 14:04:18,180 INFO    MainThread:248316 [wandb_run.py:_restore():1834] restore
2022-07-05 14:04:18,249 ERROR   MainThread:248316 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1871, in _atexit_cleanup
    self._on_finish()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1989, in _on_finish
    self._backend.interface.communicate_poll_exit()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 653, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 419, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 527, in init
    self._wl._global_run_stack[-1].finish()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1673, in finish
    return self._finish(exit_code, quiet)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1686, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1882, in _atexit_cleanup
    self._backend.cleanup()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/scratch/noelt/envs/osr/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
